export const routesConstants = {
	ROOT: "/",
	AUTH: "/auth",
	LOGIN: "/login",
	ORDERS: "/orders",
	RESET_PASSWORD: "/reset-password",
	USER: "/user",
	ADMIN: "/admin",
	HR: "/hr",
	USER_POINTS: "/points",
	USER_PRODUCTS: "/products",
	USER_ORDERS: "/orders",
	USER_REWARDS: "/rewards",
	USER_TRANSACTIONS: "/transactions",
	USER_UPDATE_CART: "/updateCart",
	UPDATE_CART: "/updateCart",
	USER_CANCEL_ORDER: "/cancelOrder",
	USER_GET_CART: "/cart",
	USER_REMOVE_CART_ITEM: "/removeCartItem",
	INVENTORY: "/inventory",
	ADMIN_DASHBOARD: "/dashboard",
	INVENTORY_UPLOAD: "/inventory/upload",
	UPDATE_ORDER_STATUS: "/updateOrderStatus",
	ADMIN_ORDER_FILTER: "/orders/filter",
	REWARD: "/rewards",
	UPLOAD: "/rewards/upload",
	REWARD_CATEGORIES: "/rewards/categories",
	REWARD_FILTER: "/rewards/filter",
	EMPLOYEES: "/employees",
	PRODUCT_COLORS: "/products/color",
	PRODUCT_SIZE: "/products/size",
	FILTER: "/filter",
	CHECKOUT: "/checkout",
	CLAIM_REWARD : "/claimReward",
	SCHEDULE_EXPIRATION: "/schedule/expiration",
};
